from typing import (
    Any,
    Callable,
    Iterator,
    Mapping,
    Optional,
    NamedTuple,
    Protocol,
    TypeVar,
    Dict,
    List,
    Tuple,
    Union
)
from requests.adapters import HTTPResponse, PreparedRequest
from responses import BaseResponse

class BaseRegistry:
    _responses = List[BaseResponse]
    def __init__(self) -> None: ...
    @property
    def registered(self) -> List[BaseResponse]: ...
    def reset(self) -> None: ...
    def find(self, request: PreparedRequest) -> Tuple[BaseResponse, List[str]]: ...
    def add(self, response: BaseResponse) -> None: ...
    def remove(self, response: BaseResponse) -> None: ...
    def replace(self, response: BaseResponse) -> None: ...

class DefaultRegistry(BaseRegistry):
    def find(self, request: PreparedRequest) -> Tuple[BaseResponse, List[str]]: ...
    def add(self, response: BaseResponse) -> None: ...
    def remove(self, response: BaseResponse) -> None: ...
    def replace(self, response: BaseResponse) -> None: ...
