name: build

on:
  push:
    branches:
      - release/**

jobs:
  dist:
    name: distribution packages
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
        with:
          python-version: 3.9

      - run: |
          pip install wheel
          python setup.py bdist_wheel sdist --formats=gztar
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ github.sha }}
          path: dist/*
